"""primera migracion

Revision ID: 086223b3dbfa
Revises: 
Create Date: 2024-11-01 19:17:37.819404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086223b3dbfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendedor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_vendedor', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=50), nullable=False),
    sa.Column('cantidad_de_productos_vendidos', sa.Integer(), nullable=False),
    sa.Column('total_ganado', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_vendedor')
    )
    op.create_table('credenciales_vendedor',
    sa.Column('id_vendedor', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('contrasena', sa.String(length=100), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('correo_contacto', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_vendedor'], ['vendedor.id_vendedor'], ),
    sa.PrimaryKeyConstraint('id_vendedor'),
    sa.UniqueConstraint('correo_contacto'),
    sa.UniqueConstraint('nombre_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credenciales_vendedor')
    op.drop_table('vendedor')
    # ### end Alembic commands ###
